var wordlists = wordlists || {};

// 48 prose words from the Airbnb JS style guide

wordlists.airbnb = [
    'amendment',
    'ascend',
    'blessed',
    'bottleneck',
    'breed',
    'cartoon',
    'cautious',
    'cleanly',
    'coerce',
    'comprehend',
    'constrain',
    'counterpart',
    'dangle',
    'emphasize',
    'flatten',
    'furnished',
    'gaming',
    'hoist',
    'inbox',
    'indentation',
    'invocation',
    'jeopardy',
    'linter',
    'minimize',
    'miracle',
    'mutating',
    'mutation',
    'newline',
    'observably',
    'optimized',
    'overused',
    'padded',
    'playbook',
    'programmatically',
    'proprietary',
    'reassign',
    'regression',
    'ripple',
    'signature',
    'silently',
    'strive',
    'subjectively',
    'synonym',
    'trailing',
    'unexpected',
    'unneeded',
    'wildcard',
    'wizard'
];
